services:
  - type: web
    name: recipe-app-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_ATLAS_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000